# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/EEE3313_projects/final_project/final_project.srcs/sources_1/bd/audio_system/ip/audio_system_auto_pc_1/audio_system_auto_pc_1.xci
# IP: The module: 'audio_system_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/EEE3313_projects/final_project/final_project.gen/sources_1/bd/audio_system/ip/audio_system_auto_pc_1/audio_system_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_system_auto_pc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/EEE3313_projects/final_project/final_project.srcs/sources_1/bd/audio_system/ip/audio_system_auto_pc_1/audio_system_auto_pc_1.xci
# IP: The module: 'audio_system_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/EEE3313_projects/final_project/final_project.gen/sources_1/bd/audio_system/ip/audio_system_auto_pc_1/audio_system_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_system_auto_pc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
