# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/EEE3313_projects/final_project/constraints/xdc.xdc

# Block Designs: bd/audio_system/audio_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system || ORIG_REF_NAME==audio_system} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_processing_system7_0_0/audio_system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_processing_system7_0_0 || ORIG_REF_NAME==audio_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_proc_sys_reset_0_0/audio_system_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_proc_sys_reset_0_0 || ORIG_REF_NAME==audio_system_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_xbar_0/audio_system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_xbar_0 || ORIG_REF_NAME==audio_system_xbar_0} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_auto_pc_2/audio_system_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_auto_pc_2 || ORIG_REF_NAME==audio_system_auto_pc_2} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_auto_pc_0/audio_system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_auto_pc_0 || ORIG_REF_NAME==audio_system_auto_pc_0} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_auto_pc_1/audio_system_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_auto_pc_1 || ORIG_REF_NAME==audio_system_auto_pc_1} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_axi_interconnect_0_0/audio_system_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_axi_interconnect_0_0 || ORIG_REF_NAME==audio_system_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_myPrescaler_0_0/audio_system_myPrescaler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_myPrescaler_0_0 || ORIG_REF_NAME==audio_system_myPrescaler_0_0} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_axi_fifo_mm_s_0_0/audio_system_axi_fifo_mm_s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==audio_system_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_axi_fifo_mm_s_1_0/audio_system_axi_fifo_mm_s_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_axi_fifo_mm_s_1_0 || ORIG_REF_NAME==audio_system_axi_fifo_mm_s_1_0} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_myI2STx_v1_0_0_0/audio_system_myI2STx_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_myI2STx_v1_0_0_0 || ORIG_REF_NAME==audio_system_myI2STx_v1_0_0_0} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_mySPIRxTx_v1_0_0_0/audio_system_mySPIRxTx_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_mySPIRxTx_v1_0_0_0 || ORIG_REF_NAME==audio_system_mySPIRxTx_v1_0_0_0} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_myPrescaler_1_0/audio_system_myPrescaler_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_myPrescaler_1_0 || ORIG_REF_NAME==audio_system_myPrescaler_1_0} -quiet] -quiet

# XDC: c:/EEE3313_projects/final_project/final_project.gen/sources_1/bd/audio_system/audio_system_ooc.xdc
